In [12]:
import numpy as np

[[0 3 0 9]
 [1 3 9 2]
 [1 5 0 7]]
[-2 -5 -9  0]
[ 2 11  9 18]


## 2.3.3 Numpy的通用函数

In [ ]:
x = np.arange(4)
print(x)
print("x       =", x)
print("x + 5   =", x+5)
print("x - 5   =", x-5)
print("x * 2   =", x*2)
print("x / 2   =", x/2)
print("x // 2  =", x//2)
print("-x      =", -x)
print("x ** 2  =", x**2)

| 运算符     | 通用函数         | 描述                             |
|-----------|-----------------|---------------------------------|
| +         |  np.add         | 加法运算（即 1 + 1 = 2）           |
| *         |  np.multiply    | 乘法运算（即 `2 * 3 = 6`）      |
| -         | `np.negative`   | 负数运算（即 `-2`）             |
| *         | `np.multiply`   | 乘法运算（即 `2 * 3 = 6`）      |
| /         | `np.divide`     | 除法运算（即 `3 / 2 = 1.5`）    |
| //        | `np.floor_divide` | 地板除法运算（floor division，即 `3 // 2 = 1`） |
| **        | `np.power`      | 指数运算（即 `2 ** 3 = 8`）     |
| %         | `np.mod`        | 模 / 余数（即 `9 % 4 = 1`）     |

In [25]:
x = np.array([-2, -3, -6, 9, 15])
np.abs(x)

array([ 2,  3,  6,  9, 15])